import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :archethic, ArchethicPlaygroundWeb.Endpoint,
  http: [
    :inet6,
    port: System.get_env("ARCHETHIC_PLAYGROUND_HTTP_PORT", "40000") |> String.to_integer()
  ],
  url: [
    host: nil,
    port: System.get_env("ARCHETHIC_PLAYGROUND_HTTP_PORT", "40000") |> String.to_integer()
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:archethic, :vsn),
  check_origin: false
